/* ─────────────────────────── boilerplate ──────────────────────────── */

export function packageJson(appSlug: string): string {
  return JSON.stringify(
    {
      name: appSlug,
      version: "0.1.0",
      private: true,
      scripts: {
        dev: "next dev",
        build: "next build",
        start: "next start",
        lint: "next lint",
      },
      dependencies: {
        next: "^15.2.0",
        react: "^19.0.0",
        "react-dom": "^19.0.0",
      },
      devDependencies: {
        "@types/node": "^20",
        "@types/react": "^19",
        "@types/react-dom": "^19",
        typescript: "^5",
        "eslint": "^8",
        "eslint-config-next": "^15.2.0",
      },
    },
    null,
    2
  );
}

export function tsconfigJson(): string {
  return JSON.stringify(
    {
      compilerOptions: {
        target: "ES2017",
        lib: ["dom", "dom.iterable", "esnext"],
        allowJs: true,
        skipLibCheck: true,
        strict: true,
        noEmit: true,
        esModuleInterop: true,
        module: "esnext",
        moduleResolution: "bundler",
        resolveJsonModule: true,
        isolatedModules: true,
        jsx: "react-jsx",
        incremental: true,
        plugins: [{ name: "next" }],
        paths: { "@/*": ["./*"] },
      },
      include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
      exclude: ["node_modules"],
    },
    null,
    2
  );
}

export function nextConfig(): string {
  return `import type { NextConfig } from "next";

const nextConfig: NextConfig = {};

export default nextConfig;
`;
}

export function appLayout(title: string): string {
  return `import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "${title}",
  description: "Generated by Intel Exchange Documentation Agent — powered by Cyware CTIX APIs",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`;
}

export function envExample(): string {
  return `# Cyware Intel Exchange Open API credentials
# Copy this file to .env.local and fill in your values.
# NEVER commit .env.local to source control.

CYWARE_BASE_URL=https://your-tenant.cyware.com/ctixapi
CYWARE_ACCESS_ID=
CYWARE_SECRET_KEY=
`;
}

/* ─────────────────────────── Cyware client ────────────────────────── */

export function clientFile(): string {
  return `import crypto from "node:crypto";

export interface CywareConfig {
  baseUrl: string;
  accessId: string;
  secretKey: string;
}

export function sign(accessId: string, secretKey: string, expires: number): string {
  const payload = \`\${accessId}\\n\${expires}\`;
  return crypto.createHmac("sha1", secretKey).update(payload).digest("base64");
}

export class CywareClient {
  constructor(private cfg: CywareConfig) {}

  private authQuery(): Record<string, string> {
    const expires = Math.floor(Date.now() / 1000) + 20;
    return {
      AccessID: this.cfg.accessId,
      Expires: String(expires),
      Signature: sign(this.cfg.accessId, this.cfg.secretKey, expires),
    };
  }

  async request<T = unknown>(opts: {
    method: string;
    path: string;
    query?: Record<string, string>;
    body?: unknown;
    headers?: Record<string, string>;
  }): Promise<{ status: number; data: T; text: string }> {
    const base = this.cfg.baseUrl.replace(/\\/$/, "");
    const path = opts.path.startsWith("/") ? opts.path : \`/\${opts.path}\`;
    const url = new URL(base + path);
    for (const [k, v] of Object.entries({ ...this.authQuery(), ...opts.query ?? {} })) {
      if (v !== undefined && v !== "") url.searchParams.set(k, v);
    }

    const isMultipart = opts.headers?.["Content-Type"]?.includes("multipart");
    const res = await fetch(url.toString(), {
      method: opts.method,
      headers: isMultipart ? opts.headers : { "Content-Type": "application/json", ...opts.headers },
      body: opts.body !== undefined ? JSON.stringify(opts.body) : undefined,
    });

    const text = await res.text();
    let data: T;
    try { data = JSON.parse(text) as T; } catch { data = text as T; }

    if (!res.ok) {
      throw new Error(\`Cyware \${opts.method} \${path} failed (\${res.status}): \${text.slice(0, 500)}\`);
    }
    return { status: res.status, data, text };
  }
}

export function cywareClientFromEnv(): CywareClient {
  const baseUrl = process.env.CYWARE_BASE_URL;
  const accessId = process.env.CYWARE_ACCESS_ID;
  const secretKey = process.env.CYWARE_SECRET_KEY;
  if (!baseUrl || !accessId || !secretKey) {
    throw new Error(
      "Missing Cyware credentials. Set CYWARE_BASE_URL, CYWARE_ACCESS_ID, and CYWARE_SECRET_KEY in .env.local"
    );
  }
  return new CywareClient({ baseUrl, accessId, secretKey });
}
`;
}
