import type { AgentAppBlueprint, AgentStepResult } from "./types";

/* ─────────────────────────── boilerplate ──────────────────────────── */

function packageJson(appSlug: string): string {
  return JSON.stringify(
    {
      name: appSlug,
      version: "0.1.0",
      private: true,
      scripts: {
        dev: "next dev",
        build: "next build",
        start: "next start",
        lint: "next lint",
      },
      dependencies: {
        next: "^15.2.0",
        react: "^19.0.0",
        "react-dom": "^19.0.0",
      },
      devDependencies: {
        "@types/node": "^20",
        "@types/react": "^19",
        "@types/react-dom": "^19",
        typescript: "^5",
        "eslint": "^8",
        "eslint-config-next": "^15.2.0",
      },
    },
    null,
    2
  );
}

function tsconfigJson(): string {
  return JSON.stringify(
    {
      compilerOptions: {
        target: "ES2017",
        lib: ["dom", "dom.iterable", "esnext"],
        allowJs: true,
        skipLibCheck: true,
        strict: true,
        noEmit: true,
        esModuleInterop: true,
        module: "esnext",
        moduleResolution: "bundler",
        resolveJsonModule: true,
        isolatedModules: true,
        jsx: "react-jsx",
        incremental: true,
        plugins: [{ name: "next" }],
        paths: { "@/*": ["./*"] },
      },
      include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
      exclude: ["node_modules"],
    },
    null,
    2
  );
}

function nextConfig(): string {
  return `import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  // Don't let lint warnings or minor type issues block deployments
  eslint: { ignoreDuringBuilds: true },
  typescript: { ignoreBuildErrors: true },
};

export default nextConfig;
`;
}

function appLayout(title: string): string {
  return `import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "${title}",
  description: "Generated by Intel Exchange Documentation Agent — powered by Cyware CTIX APIs",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`;
}

function globalsCss(): string {
  return `*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

body {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
  background: #f8fafc;
  color: #1e293b;
  line-height: 1.6;
  min-height: 100vh;
}

.container { max-width: 960px; margin: 0 auto; padding: 2rem 1rem; }

h1 { font-size: 1.875rem; font-weight: 700; letter-spacing: -0.025em; margin-bottom: 0.375rem; }
h2 { font-size: 1.125rem; font-weight: 600; margin-bottom: 0.75rem; }
h3 { font-size: 0.9375rem; font-weight: 600; margin-bottom: 0.5rem; }

.subtitle { color: #64748b; margin-bottom: 2rem; max-width: 600px; }

.card {
  background: #ffffff;
  border: 1px solid #e2e8f0;
  border-radius: 12px;
  padding: 1.5rem;
  margin-bottom: 1.5rem;
  box-shadow: 0 1px 3px rgba(0,0,0,0.04);
}

textarea, input[type="text"] {
  width: 100%;
  padding: 0.625rem 0.875rem;
  border: 1.5px solid #cbd5e1;
  border-radius: 8px;
  font-family: "SF Mono", "Fira Code", monospace;
  font-size: 0.8125rem;
  resize: vertical;
  background: #f8fafc;
  transition: border-color 0.15s;
  margin-bottom: 1rem;
}
textarea:focus, input:focus { outline: none; border-color: #3b82f6; background: #fff; box-shadow: 0 0 0 3px rgba(59,130,246,0.12); }

.btn {
  display: inline-flex; align-items: center; gap: 0.5rem;
  padding: 0.5rem 1.125rem; border-radius: 8px;
  font-weight: 600; font-size: 0.875rem; border: none; cursor: pointer;
  transition: background 0.15s, transform 0.1s;
  text-decoration: none;
}
.btn:active:not(:disabled) { transform: scale(0.98); }
.btn:disabled { opacity: 0.45; cursor: not-allowed; }
.btn-primary { background: #3b82f6; color: #fff; }
.btn-primary:hover:not(:disabled) { background: #2563eb; }
.btn-danger { background: #ef4444; color: #fff; }
.btn-danger:hover:not(:disabled) { background: #dc2626; }
.btn-ghost { background: transparent; color: #475569; border: 1.5px solid #e2e8f0; }
.btn-ghost:hover:not(:disabled) { background: #f1f5f9; }
.btn-sm { padding: 0.3rem 0.75rem; font-size: 0.8125rem; }

.toolbar { display: flex; align-items: center; gap: 0.75rem; flex-wrap: wrap; margin-bottom: 1rem; }

.badge { display: inline-flex; align-items: center; padding: 0.25rem 0.75rem; border-radius: 9999px; font-size: 0.75rem; font-weight: 600; }
.badge-blue { background: #eff6ff; color: #1d4ed8; }
.badge-green { background: #f0fdf4; color: #166534; }
.badge-red { background: #fff1f2; color: #9f1239; }
.badge-amber { background: #fffbeb; color: #92400e; }
.badge-gray { background: #f8fafc; color: #64748b; border: 1px solid #e2e8f0; }

.table-wrapper { overflow-x: auto; border-radius: 8px; border: 1px solid #e2e8f0; }
table { width: 100%; border-collapse: collapse; font-size: 0.875rem; }
th { background: #f8fafc; text-align: left; padding: 0.625rem 0.875rem; font-size: 0.6875rem; text-transform: uppercase; letter-spacing: 0.06em; color: #94a3b8; font-weight: 600; border-bottom: 1.5px solid #e2e8f0; white-space: nowrap; }
td { padding: 0.625rem 0.875rem; border-bottom: 1px solid #f1f5f9; vertical-align: middle; }
tbody tr:last-child td { border-bottom: none; }
tbody tr:hover td { background: #f8fafc; }

.row-found td { background: #f0fdf4 !important; }
.row-not-found td { background: #fff1f2 !important; }

.type-cell { font-weight: 500; color: #475569; font-size: 0.8125rem; }
.value-cell { font-family: "SF Mono", monospace; font-size: 0.8125rem; color: #0f172a; word-break: break-all; max-width: 280px; }
.id-cell { font-family: monospace; font-size: 0.75rem; color: #64748b; }

.status-found { color: #166534; font-weight: 600; }
.status-not-found { color: #9f1239; font-weight: 500; }
.status-checking { color: #2563eb; }
.status-pending { color: #94a3b8; }

.alert { padding: 0.75rem 1rem; border-radius: 8px; font-size: 0.875rem; margin-bottom: 1rem; }
.alert-error { background: #fff1f2; border: 1px solid #fecdd3; color: #9f1239; }
.alert-info { background: #eff6ff; border: 1px solid #bfdbfe; color: #1e40af; }
.alert-success { background: #f0fdf4; border: 1px solid #bbf7d0; color: #166534; }

.summary-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(140px, 1fr)); gap: 1rem; margin-bottom: 1.5rem; }
.summary-card { background: #fff; border: 1px solid #e2e8f0; border-radius: 10px; padding: 1rem; text-align: center; }
.summary-number { font-size: 2rem; font-weight: 700; line-height: 1; margin-bottom: 0.25rem; }
.summary-label { font-size: 0.75rem; color: #64748b; font-weight: 500; text-transform: uppercase; letter-spacing: 0.05em; }

.spinner { display: inline-block; width: 14px; height: 14px; border: 2px solid rgba(255,255,255,0.3); border-top-color: currentColor; border-radius: 50%; animation: spin 0.7s linear infinite; }
@keyframes spin { to { transform: rotate(360deg); } }
`;
}

function envExample(): string {
  return `# Cyware Intel Exchange Open API credentials
# Copy this file to .env.local and fill in your values.
# NEVER commit .env.local to source control.

CYWARE_BASE_URL=https://your-tenant.cyware.com/ctixapi
CYWARE_ACCESS_ID=
CYWARE_SECRET_KEY=
`;
}

/* ─────────────────────────── Cyware client ────────────────────────── */

function clientFile(): string {
  return `import crypto from "node:crypto";

export interface CywareConfig {
  baseUrl: string;
  accessId: string;
  secretKey: string;
}

function sign(accessId: string, secretKey: string, expires: number): string {
  const payload = \`\${accessId}\\n\${expires}\`;
  return crypto.createHmac("sha1", secretKey).update(payload).digest("base64");
}

export class CywareClient {
  constructor(private cfg: CywareConfig) {}

  private authQuery(): Record<string, string> {
    const expires = Math.floor(Date.now() / 1000) + 20;
    return {
      AccessID: this.cfg.accessId,
      Expires: String(expires),
      Signature: sign(this.cfg.accessId, this.cfg.secretKey, expires),
    };
  }

  async request<T = unknown>(opts: {
    method: string;
    path: string;
    query?: Record<string, string>;
    body?: unknown;
    headers?: Record<string, string>;
  }): Promise<{ status: number; data: T; text: string }> {
    const base = this.cfg.baseUrl.replace(/\\/$/, "");
    const path = opts.path.startsWith("/") ? opts.path : \`/\${opts.path}\`;
    const url = new URL(base + path);
    for (const [k, v] of Object.entries({ ...this.authQuery(), ...opts.query ?? {} })) {
      if (v !== undefined && v !== "") url.searchParams.set(k, v);
    }

    const isMultipart = opts.headers?.["Content-Type"]?.includes("multipart");
    const res = await fetch(url.toString(), {
      method: opts.method,
      headers: isMultipart ? opts.headers : { "Content-Type": "application/json", ...opts.headers },
      body: opts.body !== undefined ? JSON.stringify(opts.body) : undefined,
    });

    const text = await res.text();
    let data: T;
    try { data = JSON.parse(text) as T; } catch { data = text as T; }

    if (!res.ok) {
      throw new Error(\`Cyware \${opts.method} \${path} failed (\${res.status}): \${text.slice(0, 500)}\`);
    }
    return { status: res.status, data, text };
  }
}

export function cywareClientFromEnv(): CywareClient {
  const baseUrl = process.env.CYWARE_BASE_URL;
  const accessId = process.env.CYWARE_ACCESS_ID;
  const secretKey = process.env.CYWARE_SECRET_KEY;
  if (!baseUrl || !accessId || !secretKey) {
    throw new Error(
      "Missing Cyware credentials. Set CYWARE_BASE_URL, CYWARE_ACCESS_ID, and CYWARE_SECRET_KEY in .env.local"
    );
  }
  return new CywareClient({ baseUrl, accessId, secretKey });
}
`;
}

/* ─────────────────────── API route generators ──────────────────────── */

function searchRoute(): string {
  return `import { NextResponse } from "next/server";
import { cywareClientFromEnv } from "@/lib/cyware/client";

/** IOC type → Cyware CQL ioc_type value */
const IOC_CQL_TYPE: Record<string, string> = {
  ipv4: "ipv4-addr",
  ipv6: "ipv6-addr",
  domain: "domain-name",
  url: "url",
  email: "email-addr",
  md5: "MD5",
  sha1: "SHA-1",
  sha256: "SHA-256",
};

interface IOCRequest {
  type: string;
  value: string;
}

export async function POST(req: Request) {
  try {
    const { ioc }: { ioc: IOCRequest } = await req.json();
    const cqlType = IOC_CQL_TYPE[ioc.type];

    if (!cqlType) {
      return NextResponse.json({ found: false, error: \`Unsupported IOC type: \${ioc.type}\` });
    }

    // Sanitise value — strip any quotes to prevent CQL injection
    const safeValue = ioc.value.replace(/"/g, "").trim();
    const query = \`type = "indicator" AND ioc_type = "\${cqlType}" AND value = "\${safeValue}"\`;

    const client = cywareClientFromEnv();
    const result = await client.request<{
      results?: { id: string; tlp?: string; confidence_score?: number; value?: string }[];
      count?: number;
    }>({
      method: "POST",
      path: "ingestion/threat-data/list/",
      body: { query },
      query: { page: "1", page_size: "1" },
    });

    const first = result.data.results?.[0];
    const found = (result.data.results?.length ?? 0) > 0;

    return NextResponse.json({
      found,
      id: found ? first?.id : undefined,
      tlp: found ? first?.tlp : undefined,
      confidence_score: found ? first?.confidence_score : undefined,
      value: found ? first?.value : undefined,
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : "Search failed";
    return NextResponse.json({ error: message, found: false }, { status: 502 });
  }
}
`;
}

function createIntelRoute(): string {
  return `import { NextResponse } from "next/server";
import { cywareClientFromEnv } from "@/lib/cyware/client";

interface CreateIntelRequest {
  value: string;
  type: string;
  tlp?: string;
}

/** Frontend extractor type → Quick Add Intel \`indicators\` object key (see docs) */
const IOC_INDICATOR_KEY: Record<string, string> = {
  ipv4: "ipv4-addr",
  ipv6: "ipv6-addr",
  domain: "domain",
  url: "url",
  email: "email",
  md5: "md5",
  sha1: "sha1",
  sha256: "sha256",
};

export async function POST(req: Request) {
  try {
    const { value, type, tlp = "AMBER" }: CreateIntelRequest = await req.json();
    const indicatorKey = IOC_INDICATOR_KEY[type];

    if (!indicatorKey) {
      return NextResponse.json({ error: \`Unsupported IOC type: \${type}\` }, { status: 400 });
    }

    const safeValue = value.replace(/,/g, "").trim();
    if (!safeValue) {
      return NextResponse.json({ error: "IOC value is required" }, { status: 400 });
    }

    const client = cywareClientFromEnv();
    const result = await client.request<{ task_id?: string; details?: string }>({
      method: "POST",
      path: "conversion/quick-intel/create-stix/",
      body: {
        indicators: { [indicatorKey]: safeValue },
        metadata: { tlp, is_apply_all: true },
        title: \`Phishing IOC: \${safeValue.slice(0, 80)}\`,
        create_intel_feed: true,
      },
    });

    return NextResponse.json({
      success: true,
      taskId: result.data.task_id,
      message: result.data.details ?? "Intel submitted to Cyware",
    }, { status: result.status });
  } catch (err) {
    const message = err instanceof Error ? err.message : "Create intel failed";
    return NextResponse.json({ error: message }, { status: 502 });
  }
}
`;
}

function routeForStep(step: AgentStepResult): string {
  const queryKeys = step.spec.queryParameters
    .filter((q) => !["AccessID", "Signature", "Expires"].includes(q.name))
    .map((q) => q.name);

  const bodyNote = step.request.body
    ? "    const body = await req.json().catch(() => ({}));"
    : "    const body = undefined;";

  const queryParse =
    queryKeys.length > 0
      ? `    const { searchParams } = new URL(req.url);
    const query: Record<string, string> = {};
${queryKeys.map((k) => `    const _${k} = searchParams.get("${k}"); if (_${k}) query["${k}"] = _${k};`).join("\n")}`
      : "    const query: Record<string, string> = {};";

  return `import { NextResponse } from "next/server";
import { cywareClientFromEnv } from "@/lib/cyware/client";

/**
 * Proxy route: ${step.method} ${step.path}
 * Docs: https://intel-exchange-runnable-docs.vercel.app${step.docUrl}
 *
 * Query params: ${step.spec.queryParameters.map((q) => q.name).join(", ") || "none"}
 * Body fields:  ${step.spec.bodyParameters.map((b) => b.name).join(", ") || "none"}
 */
export async function ${step.method === "GET" ? "GET" : "POST"}(req: Request) {
  try {
${queryParse}
${bodyNote}
    const client = cywareClientFromEnv();
    const result = await client.request({
      method: "${step.method}",
      path: "${step.spec.path.startsWith("/") ? step.spec.path : "/" + step.spec.path}",
      query,
      body,
    });
    return NextResponse.json(result.data, { status: result.status });
  } catch (err) {
    const message = err instanceof Error ? err.message : "Cyware request failed";
    return NextResponse.json({ error: message }, { status: 502 });
  }
}
`;
}

/* ──────────────────────────── frontend ────────────────────────────── */

function phishingFrontend(title: string): string {
  return `"use client";

import { useState } from "react";

type IocType = "ipv4" | "ipv6" | "domain" | "url" | "email" | "md5" | "sha1" | "sha256";

interface IOC {
  type: IocType;
  value: string;
  found?: boolean;
  cywareId?: string;
  tlp?: string;
  confidenceScore?: number;
  checking?: boolean;
  creating?: boolean;
  created?: boolean;
  error?: string;
}

const IOC_LABEL: Record<IocType, string> = {
  ipv4: "IPv4",
  ipv6: "IPv6",
  domain: "Domain",
  url: "URL",
  email: "Email",
  md5: "MD5",
  sha1: "SHA-1",
  sha256: "SHA-256",
};

function extractIOCs(text: string): IOC[] {
  const seen = new Set<string>();
  const iocs: IOC[] = [];

  function add(value: string, type: IocType) {
    const key = type + ":" + value.toLowerCase();
    if (!seen.has(key)) { seen.add(key); iocs.push({ type, value }); }
  }

  // Domains — skip if only seen as an email hostname (recipient org false positive)
  const emailDomains = new Set<string>();
  for (const m of text.matchAll(/\\b[a-z0-9._%+\\-]+@([a-z0-9.\\-]+\\.[a-z]{2,})\\b/gi)) {
    emailDomains.add(m[1].toLowerCase());
  }

  // URLs first (captures full URLs before domain extraction)
  for (const m of text.matchAll(/https?:\\/\\/[^\\s<>"'\\]\\[()]+/gi)) add(m[0], "url");

  // IPv4
  for (const m of text.matchAll(/\\b(?:(?:25[0-5]|2[0-4]\\d|[01]?\\d\\d?)\\.){3}(?:25[0-5]|2[0-4]\\d|[01]?\\d\\d?)\\b/g)) {
    const parts = m[0].split(".").map(Number);
    const isPrivate =
      (parts[0] === 10) ||
      (parts[0] === 172 && parts[1] >= 16 && parts[1] <= 31) ||
      (parts[0] === 192 && parts[1] === 168) ||
      (parts[0] === 127);
    if (!isPrivate) add(m[0], "ipv4");
  }

  // Domains (not in URL, not only a recipient email hostname)
  for (const m of text.matchAll(/\\b(?:[a-z0-9](?:[a-z0-9\\-]{0,61}[a-z0-9])?\\.)+(?:com|net|org|io|co|info|biz|edu|gov|mil|[a-z]{2})\\b/gi)) {
    const domain = m[0].toLowerCase();
    if (iocs.find(i => i.type === "url" && i.value.includes(domain))) continue;
    if (emailDomains.has(domain)) continue;
    add(domain, "domain");
  }

  // Email addresses
  for (const m of text.matchAll(/\\b[a-z0-9._%+\\-]+@[a-z0-9.\\-]+\\.[a-z]{2,}\\b/gi)) add(m[0].toLowerCase(), "email");

  // SHA-256 (64 hex chars)
  for (const m of text.matchAll(/\\b[a-f0-9]{64}\\b/gi)) add(m[0].toLowerCase(), "sha256");

  // SHA-1 (40 hex chars)
  for (const m of text.matchAll(/\\b[a-f0-9]{40}\\b/gi)) add(m[0].toLowerCase(), "sha1");

  // MD5 (32 hex chars)
  for (const m of text.matchAll(/\\b[a-f0-9]{32}\\b/gi)) add(m[0].toLowerCase(), "md5");

  return iocs;
}

export default function PhishingAnalyzerPage() {
  const [emailText, setEmailText] = useState("");
  const [iocs, setIOCs] = useState<IOC[]>([]);
  const [globalError, setGlobalError] = useState<string | null>(null);
  const [checking, setChecking] = useState(false);

  function handleExtract() {
    setGlobalError(null);
    const extracted = extractIOCs(emailText);
    if (extracted.length === 0) {
      setGlobalError("No IOCs found in the pasted text. Try including IP addresses, domains, or URLs.");
      return;
    }
    setIOCs(extracted);
  }

  function updateIOC(i: number, patch: Partial<IOC>) {
    setIOCs((prev) => prev.map((item, idx) => (idx === i ? { ...item, ...patch } : item)));
  }

  async function checkAll() {
    if (iocs.length === 0) return;
    setChecking(true);
    setGlobalError(null);
    for (let i = 0; i < iocs.length; i++) {
      updateIOC(i, { checking: true, error: undefined });
      try {
        const res = await fetch("/api/cyware/search", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ ioc: { type: iocs[i].type, value: iocs[i].value } }),
        });
        const data = await res.json();
        if (!res.ok) throw new Error(data.error ?? "Search failed");
        updateIOC(i, {
          checking: false,
          found: data.found,
          cywareId: data.id,
          tlp: data.tlp,
          confidenceScore: data.confidence_score,
        });
      } catch (e) {
        updateIOC(i, { checking: false, error: e instanceof Error ? e.message : "Failed" });
      }
    }
    setChecking(false);
  }

  async function createIntel(i: number) {
    updateIOC(i, { creating: true, error: undefined });
    try {
      const ioc = iocs[i];
      const res = await fetch("/api/cyware/create-intel", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ value: ioc.value, type: ioc.type, tlp: "AMBER" }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error ?? "Create failed");
      updateIOC(i, { creating: false, created: true });
    } catch (e) {
      updateIOC(i, { creating: false, error: e instanceof Error ? e.message : "Create failed" });
    }
  }

  const checked = iocs.filter((i) => i.found !== undefined);
  const foundCount = checked.filter((i) => i.found).length;
  const notFoundCount = checked.filter((i) => !i.found).length;

  return (
    <main className="container">
      <h1>${title}</h1>
      <p className="subtitle">
        Paste phishing email content. IOCs are extracted in your browser; all Cyware lookups
        happen through secure server routes — your credentials never reach the client.
      </p>

      {/* Input */}
      <div className="card">
        <h2>Email Content</h2>
        <textarea
          rows={8}
          value={emailText}
          onChange={(e) => setEmailText(e.target.value)}
          placeholder="Paste raw email source or body here…&#10;&#10;Example: From: attacker@evil-domain.com&#10;Visit http://malware.example.com/payload&#10;C2: 198.51.100.42"
        />
        <div className="toolbar">
          <button
            type="button"
            onClick={handleExtract}
            disabled={!emailText.trim()}
            className="btn btn-primary"
          >
            Extract IOCs
          </button>
          {iocs.length > 0 && (
            <button
              type="button"
              onClick={checkAll}
              disabled={checking}
              className="btn btn-ghost"
            >
              {checking ? <><span className="spinner" /> Checking…</> : "Check all in Cyware"}
            </button>
          )}
        </div>
      </div>

      {globalError && <div className="alert alert-error">{globalError}</div>}

      {/* Summary */}
      {iocs.length > 0 && checked.length > 0 && (
        <div className="summary-grid">
          <div className="summary-card">
            <div className="summary-number">{iocs.length}</div>
            <div className="summary-label">IOCs found</div>
          </div>
          <div className="summary-card">
            <div className="summary-number" style={{ color: "#166534" }}>{foundCount}</div>
            <div className="summary-label">In Cyware</div>
          </div>
          <div className="summary-card">
            <div className="summary-number" style={{ color: "#9f1239" }}>{notFoundCount}</div>
            <div className="summary-label">Not in Cyware</div>
          </div>
        </div>
      )}

      {/* Results table */}
      {iocs.length > 0 && (
        <div className="card" style={{ padding: 0 }}>
          <div className="table-wrapper">
            <table>
              <thead>
                <tr>
                  <th>Type</th>
                  <th>Value</th>
                  <th>Status</th>
                  <th>TLP</th>
                  <th>Risk Score</th>
                  <th>Cyware ID</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
                {iocs.map((ioc, i) => (
                  <tr
                    key={i}
                    className={ioc.found === true ? "row-found" : ioc.found === false ? "row-not-found" : ""}
                  >
                    <td className="type-cell">
                      <span className="badge badge-gray">{IOC_LABEL[ioc.type]}</span>
                    </td>
                    <td className="value-cell">{ioc.value}</td>
                    <td>
                      {ioc.checking ? (
                        <span className="status-checking"><span className="spinner" style={{ borderTopColor: "#2563eb" }} /> Checking</span>
                      ) : ioc.error ? (
                        <span style={{ color: "#dc2626", fontSize: "0.8rem" }}>{ioc.error}</span>
                      ) : ioc.found === true ? (
                        <span className="status-found">✓ Found</span>
                      ) : ioc.found === false ? (
                        <span className="status-not-found">✗ Not found</span>
                      ) : (
                        <span className="status-pending">—</span>
                      )}
                    </td>
                    <td>
                      {ioc.tlp ? (
                        <span className={\`badge \${ioc.tlp === "RED" ? "badge-red" : ioc.tlp === "GREEN" ? "badge-green" : "badge-amber"}\`}>
                          {ioc.tlp}
                        </span>
                      ) : "—"}
                    </td>
                    <td>{ioc.confidenceScore ?? "—"}</td>
                    <td className="id-cell">{ioc.cywareId ? ioc.cywareId.slice(0, 8) + "…" : "—"}</td>
                    <td>
                      {ioc.found === false && !ioc.created && (
                        <button
                          type="button"
                          onClick={() => createIntel(i)}
                          disabled={ioc.creating}
                          className="btn btn-primary btn-sm"
                        >
                          {ioc.creating ? "Creating…" : "Add to Cyware"}
                        </button>
                      )}
                      {ioc.created && <span className="status-found" style={{ fontSize: "0.8rem" }}>✓ Created</span>}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}
    </main>
  );
}
`;
}

function genericFrontend(title: string, steps: AgentStepResult[]): string {
  const apiRoutes = steps
    .map(
      (s) =>
        `  { label: ${JSON.stringify(s.title)}, method: ${JSON.stringify(s.method)}, href: "/api/cyware/${s.slug.replace(/\//g, "-")}", path: ${JSON.stringify(s.path)}, docs: ${JSON.stringify("https://intel-exchange-runnable-docs.vercel.app" + s.docUrl)} }`
    )
    .join(",\n");

  return `"use client";

import { useState } from "react";

const STEPS = [
${apiRoutes}
];

interface StepResult {
  label: string;
  status: number;
  data: unknown;
  error?: string;
  durationMs: number;
}

export default function CywareWorkflowPage() {
  const [results, setResults] = useState<Record<number, StepResult>>({});
  const [running, setRunning] = useState<number | null>(null);
  const [body, setBody] = useState<Record<number, string>>(
    Object.fromEntries(STEPS.map((_, i) => [i, ""]))
  );

  async function runStep(i: number) {
    setRunning(i);
    const step = STEPS[i];
    const t0 = Date.now();
    try {
      let parsedBody: unknown;
      if (step.method !== "GET" && body[i]?.trim()) {
        try { parsedBody = JSON.parse(body[i]); } catch { throw new Error("Invalid JSON in request body"); }
      }
      const res = await fetch(step.href, {
        method: step.method,
        headers: step.method !== "GET" ? { "Content-Type": "application/json" } : undefined,
        body: parsedBody !== undefined ? JSON.stringify(parsedBody) : undefined,
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error ?? \`Step \${i + 1} failed (\${res.status})\`);
      setResults((prev) => ({ ...prev, [i]: { label: step.label, status: res.status, data, durationMs: Date.now() - t0 } }));
    } catch (e) {
      setResults((prev) => ({
        ...prev,
        [i]: { label: step.label, status: 0, data: null, error: e instanceof Error ? e.message : "failed", durationMs: Date.now() - t0 },
      }));
    }
    setRunning(null);
  }

  async function runAll() {
    for (let i = 0; i < STEPS.length; i++) await runStep(i);
  }

  const completedCount = Object.keys(results).length;

  return (
    <main className="container">
      <h1>${title}</h1>
      <p className="subtitle">
        Secure Next.js app calling Cyware Intel Exchange APIs from server routes.
        Credentials live in environment variables only.
      </p>

      <div className="card">
        <div className="toolbar">
          <button type="button" onClick={runAll} disabled={running !== null} className="btn btn-primary">
            {running !== null ? <><span className="spinner" /> Running step {running + 1} of ${steps.length}…</> : "Run all steps"}
          </button>
          {completedCount > 0 && (
            <span className="badge badge-blue">{completedCount} / ${steps.length} complete</span>
          )}
        </div>
      </div>

      <div style={{ display: "flex", flexDirection: "column", gap: "1rem" }}>
        {STEPS.map((step, i) => {
          const result = results[i];
          const busy = running === i;
          return (
            <div key={i} className="card">
              <div className="toolbar" style={{ marginBottom: "0.5rem" }}>
                <span className="badge badge-gray">Step {i + 1}</span>
                <strong>{step.label}</strong>
                <code style={{ fontSize: "0.75rem", color: "#0284c7" }}>{step.method} {step.path}</code>
                <a href={step.docs} target="_blank" rel="noreferrer" style={{ fontSize: "0.75rem", color: "#64748b", textDecoration: "underline" }}>
                  docs ↗
                </a>
                <button
                  type="button"
                  onClick={() => runStep(i)}
                  disabled={busy || running !== null}
                  className="btn btn-ghost btn-sm"
                  style={{ marginLeft: "auto" }}
                >
                  {busy ? <><span className="spinner" /> Running…</> : "Run step"}
                </button>
              </div>

              {step.method !== "GET" && (
                <div style={{ marginBottom: "0.75rem" }}>
                  <label style={{ fontSize: "0.75rem", fontWeight: 600, color: "#64748b", textTransform: "uppercase", letterSpacing: "0.05em", display: "block", marginBottom: "0.375rem" }}>
                    Request body (JSON)
                  </label>
                  <textarea
                    rows={4}
                    value={body[i]}
                    onChange={(e) => setBody((prev) => ({ ...prev, [i]: e.target.value }))}
                    placeholder='{ "query": "type = \\"indicator\\"" }'
                    style={{ marginBottom: 0 }}
                  />
                </div>
              )}

              {result && (
                <div className={\`alert \${result.error ? "alert-error" : "alert-success"}\`} style={{ marginTop: "0.5rem" }}>
                  <div style={{ display: "flex", justifyContent: "space-between", marginBottom: "0.375rem" }}>
                    <strong>{result.error ? "Error" : \`Status \${result.status}\`}</strong>
                    <span style={{ fontSize: "0.75rem", opacity: 0.7 }}>{result.durationMs}ms</span>
                  </div>
                  <pre style={{ fontSize: "0.75rem", overflow: "auto", maxHeight: "200px", whiteSpace: "pre-wrap", wordBreak: "break-all" }}>
                    {result.error ?? JSON.stringify(result.data, null, 2)}
                  </pre>
                </div>
              )}
            </div>
          );
        })}
      </div>
    </main>
  );
}
`;
}

/* ────────────────────────────── README ───────────────────────────── */

function readme(title: string, steps: AgentStepResult[]): string {
  const stepList = steps
    .map((s) => `- **Step ${s.order}** — \`${s.method} ${s.spec.path}\` — [${s.title}](https://intel-exchange-runnable-docs.vercel.app${s.docUrl})`)
    .join("\n");

  return `# ${title}

> Generated by the [Intel Exchange Documentation Agent](https://intel-exchange-runnable-docs.vercel.app/agent).
> All API calls reference documented Cyware endpoints — no hallucinated APIs.

## Quick start

\`\`\`bash
cp .env.example .env.local   # add your Cyware credentials
npm install
npm run dev                   # http://localhost:3000
\`\`\`

## Environment variables

| Variable | Description |
|----------|-------------|
| \`CYWARE_BASE_URL\` | Your tenant API root, e.g. \`https://your-tenant.cyware.com/ctixapi\` |
| \`CYWARE_ACCESS_ID\` | Access ID from Integrators CSV |
| \`CYWARE_SECRET_KEY\` | Secret Key from Integrators CSV |

**Never commit \`.env.local\`.**

## Architecture

\`\`\`
Browser (React)
  ↓  fetch /api/cyware/*   (no Cyware credentials in browser)
Next.js Server
  ↓  HMAC-signed requests
Cyware Intel Exchange Open API
\`\`\`

## API workflow

${stepList}

## Deployment

### Vercel (recommended)

1. Push to GitHub
2. Import to [vercel.com](https://vercel.com)
3. Set env vars in Project → Settings → Environment Variables
4. Deploy

### Manual

\`\`\`bash
npm run build
npm start
\`\`\`

Set \`CYWARE_BASE_URL\`, \`CYWARE_ACCESS_ID\`, \`CYWARE_SECRET_KEY\` in your host's environment.
`;
}

/* ─────────────────────── main export ──────────────────────────────── */

export function generateAppBlueprint(
  query: string,
  title: string,
  description: string,
  steps: AgentStepResult[]
): AgentAppBlueprint {
  const appSlug = title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
  const isPhishing = /phishing|email/i.test(query);

  const architecture = [
    "Browser (React UI)",
    "  ↓ fetch /api/cyware/*",
    "Next.js API Routes (server)",
    "  ↓ HMAC-signed requests",
    "Cyware Intel Exchange Open API",
  ].join("\n");

  const boilerplate = [
    { path: "package.json", language: "json", description: "Project dependencies and scripts", code: packageJson(appSlug) },
    { path: "tsconfig.json", language: "json", description: "TypeScript configuration", code: tsconfigJson() },
    { path: "next.config.ts", language: "typescript", description: "Next.js configuration", code: nextConfig() },
    { path: "app/layout.tsx", language: "typescript", description: "Root layout with metadata", code: appLayout(title) },
    { path: "app/globals.css", language: "css", description: "Global styles", code: globalsCss() },
    { path: ".env.example", language: "bash", description: "Environment variables template", code: envExample() },
    { path: "lib/cyware/client.ts", language: "typescript", description: "Reusable Cyware API client with HMAC auth", code: clientFile() },
  ];

  const stepRoutes = steps.map((step) => ({
    path: `app/api/cyware/${step.slug.replace(/\//g, "-")}/route.ts`,
    language: "typescript",
    description: `${step.method} ${step.spec.path} — ${step.title}`,
    code: routeForStep(step),
  }));

  const extraRoutes = isPhishing
    ? [
        { path: "app/api/cyware/search/route.ts", language: "typescript", description: "IOC lookup in Cyware threat data", code: searchRoute() },
        { path: "app/api/cyware/create-intel/route.ts", language: "typescript", description: "Create new intel for unknown IOCs", code: createIntelRoute() },
      ]
    : [];

  const frontend = {
    path: "app/page.tsx",
    language: "typescript",
    description: isPhishing ? "Phishing analyzer UI with IOC extraction + Cyware lookup" : "Workflow runner UI",
    code: isPhishing ? phishingFrontend(title) : genericFrontend(title, steps),
  };

  const files = [...boilerplate, ...stepRoutes, ...extraRoutes, frontend, {
    path: "README.md",
    language: "markdown",
    description: "Setup and deployment instructions",
    code: readme(title, steps),
  }];

  return {
    title,
    description,
    architecture,
    setupInstructions:
      "1. Copy .env.example → .env.local and add your Cyware credentials. 2. npm install && npm run dev. 3. For production: deploy to Vercel and set the 3 env vars in Project Settings.",
    envExample: envExample(),
    files,
  };
}

export function appTitleFromQuery(query: string): string {
  if (/phishing/i.test(query)) return "Phishing Email Analyzer";
  if (/stix/i.test(query)) return "STIX Import Portal";
  if (/threat.*dashboard|dashboard.*threat/i.test(query)) return "Threat Intel Dashboard";
  const m = query.match(/build\s+(?:a\s+)?(.{3,60}?)(?:\s+app|\s+website|\s+dashboard|$)/i);
  if (m?.[1]) return m[1].replace(/\b\w/g, (c) => c.toUpperCase()).trim();
  return "Cyware Integration App";
}
